services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./nginx-config.txt:/etc/nginx/conf.d/default.conf
      - ./web-app-code.py:/app/web-app-code.py
